### ISSUE TITLE
Can't alter comparison input values

### ISSUE THREAD

**Issue by ctk21** [ocaml-bench/sandmark-nightly#1]
I tried to use the parallel_nightly.ipynb notebook to view some comparisons. 

However if I try to enter data into this cell using the dropdown:
<img width="906" alt="Screenshot 2021-06-14 at 09 29 44" src="https://user-images.githubusercontent.com/1682628/121863685-03a28080-ccf4-11eb-8087-6055fd49fb21.png">
then when I recompute the cell (or whole workbook) it forces it back to the initial value.

**Comment by kayceesrk** [comment]
The choices are not sticky, and recomputing the cell or the whole notebook would reset the options. This is the expected behaviour, though making the choices sticky would be a useful feature. It is recommended that after the option is chosen, one can recompute the rest of the notebook by clicking on the subsequent cell and doing `Cell -> Run all below`.

**Comment by kayceesrk** [comment]
Closed this issue as this is the expected behavior from jupyter evaluation semantics.
