### ISSUE TITLE
WebUI needs to filter out the missing benchmarks

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#18]
The webUI needs to filter out the missing benchmarks. Otherwise, the results are not visible.

![image](https://user-images.githubusercontent.com/410484/134282518-caa88311-1057-49a5-b80b-abc12b0083f1.png)

Cubicle and Coq benchmarks don't build on the multicore versions (`4.12+domains+effects` and `4.12+domains`) (c.f #16) but do build on stock OCaml. So the WebUI needs to filter out the benchmarks that are not present in all of the variants being compared.

**Comment by shubhamkumar13** [comment]
This issue is resolved in commit https://github.com/ocaml-bench/sandmark-nightly/commit/f02957b30cf928ab18b9e3b863eeb6d7d601a025 <br>
<img width="882" alt="Screenshot 2021-09-29 at 1 55 51 AM" src="https://user-images.githubusercontent.com/13629677/135160544-44a5b99d-64b7-4c18-a5b1-c8342a74f4d3.png">
