### ISSUE TITLE
Parallel nightly notebook does not plot all the chosen variants

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-bench/sandmark-nightly#3]
I had chosen two variants:

![image](https://user-images.githubusercontent.com/410484/124217336-ccb2d400-db15-11eb-9732-5f9f005dad2c.png)

Bu the graphs are only plotted for one:

![image](https://user-images.githubusercontent.com/410484/124217416-ee13c000-db15-11eb-9917-a8f7cf85697e.png)

The notebook should be plotting all the variants chosen.

**Comment by shubhamkumar13** [comment]
This issue was because of the bench file with timestamp `20210701_200721` being empty. I've removed the the bench file and it is plotting all the timestamps

with 2 variants
![Screenshot from 2021-07-08 04-35-15](https://user-images.githubusercontent.com/13629677/124839935-6b708200-dfa7-11eb-84f5-fb5e9e3162d9.png)
![Screenshot from 2021-07-08 04-36-07](https://user-images.githubusercontent.com/13629677/124839941-6f9c9f80-dfa7-11eb-8a22-6fc15ee20671.png)

with 5 variants
![Screenshot from 2021-07-08 04-45-12](https://user-images.githubusercontent.com/13629677/124839964-79be9e00-dfa7-11eb-9359-7b4769bfe99b.png)
![Screenshot from 2021-07-08 04-45-37](https://user-images.githubusercontent.com/13629677/124839969-7b886180-dfa7-11eb-9b2e-a2bcf6ca0aa8.png)

I think this issue can be closed now.

**Comment by kayceesrk** [comment]
Thanks.
