### ISSUE TITLE
Sandmark-nightly home page error

### ISSUE THREAD

**Issue by shakthimaan** [ocaml-bench/sandmark-nightly#46]
![sandmark-nightly-home-page-path-error](https://user-images.githubusercontent.com/312622/154415844-67d6e5d8-69ba-422c-8b89-67827d711b12.png)

Kindly avoid pushing code directly to repository, unless it is a hotfix. Create PRs for changes always.
https://github.com/ocaml-bench/sandmark-nightly/commit/95df25f8503745ce53903326d222904ffa2c734a
https://github.com/ocaml-bench/sandmark-nightly/commit/75cea2dddca6c1e4596ba0ed21e125dff18d3af8

**Comment by shakthimaan** [comment]
I now see `NoSuchPathError: /sandmark` in the home page.

**Comment by shubhamkumar13** [comment]
For now I've pushed a hotfix -> https://github.com/ocaml-bench/sandmark-nightly/commit/25161ae0792838b3623219081e055e4e3444ef7e 
This error was occurring because I was trying to access sandmark directory to get the branch and latest commit id of nightly
Which I later realised is not going to be a part of sandmark-nightly and hence it wouldn't be able to find the directory.

The following screenshot is after pushing the hotfix to sandmark-nightly, this is from `sandmark.ocamllabs.io`


<img width="919" alt="Screenshot 2022-02-17 at 10 24 47 PM" src="https://user-images.githubusercontent.com/13629677/154531163-68df5ac2-e209-4bd4-9e76-80eee343dc2d.png">

I'll reopen https://github.com/ocaml-bench/sandmark-nightly/issues/41

**Comment by shubhamkumar13** [comment]
this issue can be closed
